server:
  port: 8761
  
security:
  basic:
    #关闭安全验证
    enabled: false
  user:
    name: admin
    password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/